//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

public class GameOverController : MonoBehaviour
{
	void Update() {
		if (Input.GetButton("Exit")) {
			Application.Quit();
		}
	}
}
