//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class ReturnableScreenController : MonoBehaviour
{
	const float MINIMUM_TIME = 2f;
	bool canGoBack = false;

	public string levelToReturn;

	IEnumerator StayHere() {
		yield return new WaitForSeconds(MINIMUM_TIME);
		canGoBack = true;
	}

	void Start() {
		if (levelToReturn == "") {
			levelToReturn = "main-menu";
		}
		StartCoroutine(StayHere());
	}

	void Update() {
		if (canGoBack && Input.anyKey) {
			Application.LoadLevel(levelToReturn);
		}
	}
}
