//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class ReturnableScreenController : MonoBehaviour
{
	const float MINIMUM_TIME = 2f;
	bool canGoBack = false;

	public string levelToReturn;

	IEnumerator StayHere()
	{
		yield return new WaitForSeconds(MINIMUM_TIME);
		canGoBack = true;
	}

	IEnumerator GoBack()
	{
		Animator animator =  GameObject
				.FindGameObjectWithTag("screen")
				.GetComponent<Animator>();

		// if there is a animator, execute it
		if (animator)
		{
			animator.SetTrigger("close");
			yield return new WaitForSeconds(0.5f);
		}

		Application.LoadLevel(levelToReturn);
	}

	void Start()
	{
		if (levelToReturn == "")
			levelToReturn = "main-menu";

		StartCoroutine(StayHere());
	}

	void Update()
	{
		if ( canGoBack &&
		    (  Input.GetButton("Jump")
			|| Input.GetButton("Enter")
			|| Input.GetButton("Fire1") ) )
		{
			canGoBack = false;
			StartCoroutine(GoBack());
		}
	}
}
